### ISSUE TITLE
Will this become official?

### ISSUE THREAD

**Issue by neverfox** [sethrfore/homebrew-r-srf#1]
This seems like a rather serious issue with the default brew r, and this repo really solved by problem with packages that need tcl/tk support. Are they any efforts in progress to make that support an option for the main brew package? Have you tried submitting a pull request to homebrew?

**Comment by sethrfore** [comment]
Homebrew maintainers have made a deliberate decision to transition away from being a build-from-source package manager to a binary package manager. This is in part to increase the overall reliability of formula installation by minimizing compatibility/bug issues related to downstream dependencies.

In the case of R, providing tcl/tk support depends on X11/xQuartz which is not natively installed on MacOS (see this [discussion](https://discourse.brew.sh/t/r-installs-on-high-sierra-without-tcl-tk-support/1190/17?u=srfore)). As such, I do not intend on submitting a pull request. Although, I will continue to maintain this tap. 

In any case, I'm glad to hear the use of this tap provided a solution to your issues!

**Comment by sethrfore** [comment]
I think this would be the most straight forward [documentation](https://docs.brew.sh/Building-Against-Non-Homebrew-Dependencies) on this. I suspect _We don't like binary formulae_ is in reference to apps (like X11/Xquartz) that are only distributed as binaries and correspondingly [installed](https://github.com/caskroom/homebrew-cask#homebrew-cask) via `brew cask ...`. Since these binaries are not compiled/bottled using strictly Homebrew dependencies, when installed they may place files in locations inside/outside Homebrew's prefix that overwrite/duplicate files associated with an installed formula and/or link to different versions of an installed formula. This can create all kinds of downstream dependency issues which amounts to lots of work for maintainers. Finally, since most people have been installing binaries anyway, they have decided to streamline the process by only allowing formula dependencies that can be satisfied within Homebrew while encouraging those requiring custom formula to create and maintain their own tap as is being done here. While I'm no expert, this is my understanding of the issue.
