### ISSUE TITLE
cairo.rb formula collides with Homebrew in dependencies

### ISSUE THREAD

**Issue by tobadia** [sethrfore/homebrew-r-srf#42]
Hey,

Thanks for maintaining this repo over the past few years. I've recently come across an issue since switching to your r-aqua branch that proved much more easy/efficient when working on Catalina+.

Whenever `cairo.rb` is indicated as a dependency for a formulae, Homebrew assumes it should be the original at `homebrew-core/cairo.rb`. However, since `sethrfore/r-srf/cairo.rb` is named identically, this kind of stuff happens :

```
[...]
==> Installing dependencies for ffmpeg: aom, cairo, gobject-introspection, harfbuzz, libvpx, rubberband and x265
==> Installing ffmpeg dependency: aom
==> Pouring aom-3.0.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/aom/3.0.0: 22 files, 12.5MB
Error: cairo is already installed from sethrfore/r-srf!
Please `brew uninstall cairo` first."
```

I can easily `brew uninstall cairo`, update everything, then `brew uninstall cairo && brew install homebrew-core/cairo.rb` but that's not ideal as it is boudn to happen regularly. Is there any way to indicate Homebrew that any reference to `cairo.rb` should pin to `sethrfore/r-srf/cairo.rb` ?

Thanks and cheers,
Thomas

**Comment by sethrfore** [comment]
Thanks for the feedback. I've also encountered this issue and, yes, it is annoying. The reason I haven't given the formula a unique name is due to confusion downstream when installing external R packages. R packages usually look for dependencies based on their standard name and location and do not always find the correct paths even if they are correctly specified in your Makeconf file (e.g., /usr/local/opt/r/lib/R/etc/Makeconf). As a result, a given R package might pick up the home-brew formula installed with different options resulting in package compiling errors. 

I'm with you that this can be annoying. If anything, the current strategy is biased towards stabilizing R package builds at the expense of other home-brew formula installations. There certainly may be better ways of dealing with this that solves all problems, but that has so far been beyond my expertise. However, thanks for the feedback and I'm always open to suggestions that provide stable solutions to problems.
