### ISSUE TITLE
Failed to download pre-compiled bottle

### ISSUE THREAD

**Issue by lwshang** [sethrfore/homebrew-r-srf#5]
The message is as below:

```
==> Installing r from sethrfore/r-srf
==> Downloading https://homebrew.bintray.com/bottles-r-srf/r-3.5.1.high_sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "r"
Download failed: https://homebrew.bintray.com/bottles-r-srf/r-3.5.1.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

**Comment by sethrfore** [comment]
Because this tap depends on external dependencies that are not supported by Homebrew anymore (X11), this formula must be compiled from source with any selected options: `brew install -s sethrfore/r-srf/r`. If installing from source doesn’t fix your problem, let me know. 

Aside from that, I'll remove the option to install bottled version since it has always been non-functional.
