### ISSUE TITLE
installation was stoped when updated R to v3.5.2

### ISSUE THREAD

**Issue by tkosaka1976** [sethrfore/homebrew-r-srf#8]
I tried to install R-3.5.2 but the process was stoped in this line.
>./configure: line 38486: /System/Library/Frameworks/Tcl.framework/tclConfig.sh: No such file or directory

What things should I do to solve this problem?

**Comment by sethrfore** [comment]
There are a couple likely issues both of which are addressed in the installation directions. The first is that Command Line Tools must be installed in order for these files to be present regardless of your macOS. Second, if you have upgraded to macOS 10.14 (Mojave) there is an additional step to install the necessary header files in the appropriate locations:

`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`

For further info on this step, consult the [R Installation and Administration](https://cran.r-project.org/doc/manuals/r-devel/R-admin.html#macOS) manual.

If after following the installation instructions you still have problems, let me know and I'll reopen the issue.

**Comment by tkosaka1976** [comment]
Thanks. It worked!

**Comment by tkosaka1976** [comment]
Probably, this problem re-happen in Catalina(10.15) again.
If you know how to do it, please tell me.

**Comment by sethrfore** [comment]
This issue was previously closed and I'll likely close it again since the problem you're now having relates to other currently open issues (#17, #16). If Tcl-Tk functionality is required, there are some potential solutions given in #17 and implemented in a development branch (dev-tcltk) with some instructions given in the formula code. Changes in Xcode and CLTs have caused a few issues that are currently unresolved except in a more or less hack fashion. After catching up on these issues in the referenced links, if you still have a question, I suggest opening a new issue.
